baseURL = "https://sebfio.github.io/fydp_website/"
languageCode = "en-us"
title = "ShopTrac's Blog"
theme = "aether"
publishDir = "docs"

[params]
brand = "ShopTrac"
description = "The biggest revolution to physical retail since Amazon Go"
homeimg = "junk.png"
bgimg = "wasteBanner.jpg"
